name: Helm

on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Chart Checkout
        uses: actions/checkout@v2

      - name: Helm Installation
        uses: azure/setup-helm@v1.1
        with:
          version: v3.8.2

      - name: Helm Repository Checkout
        uses: actions/checkout@v2
        with:
          repository: yourorg/helm-chart-repository
          token: ${{ secrets.DEVOPS_BOT_GH_TOKEN }}
          fetch-depth: 0
          persist-credentials: true
          ref: main
          path: helm-chart-repository

      - name: Helm Package
        run: helm package ./deploy/helm --version "0.1.0+$(git rev-parse --short "$GITHUB_SHA")" -d helm-chart-repository

      - name: Helm Push
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_BOT_GH_TOKEN }}
        run: |
          git config --global user.email "devopsbot@cmlinsight.com"
          git config --global user.name "devopsbot"
          CHART_PACKAGE_NAME="godaddy-webhook-0.1.0+$(git rev-parse --short "$GITHUB_SHA").tgz"
          cd helm-chart-repository
          git add "$CHART_PACKAGE_NAME"
          git commit -m "$CHART_PACKAGE_NAME"
          git push origin main
